name: Feature Request
description: Suggest a new feature or data type
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Description
      description: What would you like added?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use Case
      description: How would you use this feature?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: Any relevant HealthKit documentation links or examples?
